(function(root,factory){const api=factory(root.CauldronIngredients);if(typeof module==="object"&&module.exports)module.exports=api;root.CauldronGame=api})(typeof globalThis!=="undefined"?globalThis:this,function(data){"use strict";
function createState(config,firstId){return{config,sequence:firstId?[firstId]:[],players:config.players.map(name=>({name,lives:config.lives,score:0,out:false})),turn:0,inputIndex:0,phase:"show"}}
function activePlayers(s){return s.players.map((p,i)=>({...p,index:i})).filter(p=>!p.out)}
function currentPlayer(s){let guard=0;while(s.players[s.turn].out&&guard++<s.players.length)s.turn=(s.turn+1)%s.players.length;return s.turn}
function beginTurn(s,randomId){s.inputIndex=0;s.phase="show";if(s.config.mode==="generated")s.sequence.push(randomId);return s.sequence}
function input(s,id){if(s.phase!=="input")return{type:"locked"};if(s.inputIndex<s.sequence.length){if(id!==s.sequence[s.inputIndex])return fail(s);s.inputIndex++;if(s.inputIndex===s.sequence.length&&s.config.mode==="generated"){s.players[currentPlayer(s)].score++;s.phase="done";return{type:"success"}}return{type:"progress"}}s.sequence.push(id);s.players[currentPlayer(s)].score++;s.phase="done";return{type:"success",added:id}}
function fail(s){const p=s.players[currentPlayer(s)];p.lives--;if(p.lives<=0)p.out=true;s.phase="done";return{type:"failure",eliminated:p.out}}
function nextPlayer(s){s.turn=(s.turn+1)%s.players.length;currentPlayer(s);return activePlayers(s).length<=1||s.sequence.length>=s.config.limit}
function winners(s){const active=activePlayers(s);if(active.length===1)return[active[0].index];const max=Math.max(...s.players.map(p=>p.score));return s.players.map((p,i)=>p.score===max?i:-1).filter(i=>i>=0)}
const api={createState,activePlayers,currentPlayer,beginTurn,input,fail,nextPlayer,winners};if(typeof document==="undefined")return api;
const $=id=>document.getElementById(id),screens=["setup","handoff","game","result","finish"];let state,pool=[],locked=true,showToken=0;
function show(id){screens.forEach(x=>$(x).hidden=x!==id);scrollTo({top:0,behavior:"smooth"})}
function renderPlayers(){const n=+$("playerCount").value;$("players").innerHTML=Array.from({length:n},(_,i)=>`<input class="player-name" value="Hráč ${i+1}" aria-label="Jméno hráče ${i+1}">`).join("")}
function setupSets(){$("set").innerHTML=Object.entries(data.sets).map(([k,v])=>`<option value="${k}">${v.name}</option>`).join("")}
function randomId(){return pool[Math.floor(Math.random()*pool.length)]}
function ingredient(id){return data.ingredients.find(x=>x.id===id)}
function handoff(){const p=state.players[currentPlayer(state)];$("handoffText").textContent=`Předat zařízení hráči ${p.name}`;show("handoff")}
function renderStatus(){const p=currentPlayer(state);$("turnName").textContent=state.players[p].name;$("length").textContent=`${state.sequence.length} / ${state.config.limit}`;$("livesStatus").innerHTML=state.players.map((x,i)=>`<span class="life ${x.out?"out":""}">${x.name}: ${"❤️".repeat(x.lives)} ${x.score} b.</span>`).join("")}
function renderIngredients(){$("ingredients").innerHTML=pool.map(id=>{const x=ingredient(id);return`<button class="ingredient" data-id="${id}" disabled>${x.image?`<img src="${x.image}" alt="${x.alt}" onerror="this.replaceWith(document.createTextNode('${x.fallback}'))">`:`<span aria-hidden="true">${x.fallback}</span>`}${x.name}</button>`}).join("")}
async function showSequence(){const token=++showToken,sequence=beginTurn(state,randomId());renderStatus();locked=true;setButtons(true);$("instruction").textContent="Sleduj řadu symbolů i názvů.";for(const id of sequence){if(token!==showToken)return;const x=ingredient(id);$("display").textContent=`${x.fallback} ${x.name}`;const b=document.querySelector(`[data-id="${id}"]`);b?.classList.add("flash");await wait(state.config.speed);b?.classList.remove("flash");$("display").textContent="✨";await wait(170)}if(token!==showToken)return;state.phase="input";locked=false;$("display").textContent="Teď ty!";$("instruction").textContent=state.config.mode==="shared"?"Zopakuj řadu a potom přidej jednu přísadu.":"Zopakuj celou řadu.";setButtons(false)}
function wait(ms){return new Promise(r=>setTimeout(r,ms))}
function setButtons(disabled){document.querySelectorAll(".ingredient").forEach(b=>b.disabled=disabled)}
function choose(id){if(locked)return;const r=input(state,id);if(r.type==="progress")return;if(r.type==="failure"){locked=true;setButtons(true);const p=state.players[currentPlayer(state)];$("resultTitle").textContent=r.eliminated?`${p.name} vypadává!`:"To nebyla správná přísada";$("resultText").textContent=r.eliminated?"Došly ti životy.":"Ztrácíš jeden život.";show("result")}if(r.type==="success"){locked=true;setButtons(true);$("resultTitle").textContent="Kouzlo se povedlo! ✨";$("resultText").textContent=r.added?`Do řady přibývá ${ingredient(r.added).name}.`:"Celá řada byla správně.";show("result")}}
function finishGame(){const win=winners(state);$("final").innerHTML=state.players.map((p,i)=>`<div class="final-row ${win.includes(i)?"winner":""}">${p.name}: ${p.score} bodů, ${p.lives} životů ${win.includes(i)?"🏆":""}</div>`).join("");show("finish")}
function advance(){nextPlayer(state)?finishGame():handoff()}
function start(same=false){showToken++;if(!same){pool=data.sets[$("set").value].ids;const config={players:[...document.querySelectorAll(".player-name")].map((x,i)=>x.value.trim()||`Hráč ${i+1}`),lives:+$("lives").value,speed:+$("speed").value,mode:$("mode").value,limit:+$("limit").value};state=createState(config,config.mode==="shared"?randomId():null)}else state=createState(state.config,state.config.mode==="shared"?randomId():null);renderIngredients();handoff()}
function newSettings(){showToken++;state=null;renderPlayers();show("setup")}
setupSets();renderPlayers();$("playerCount").onchange=renderPlayers;$("start").onclick=()=>start(false);$("confirm").onclick=()=>{show("game");showSequence()};$("ingredients").onclick=e=>{const b=e.target.closest(".ingredient");if(b)choose(b.dataset.id)};$("next").onclick=advance;$("again").onclick=()=>start(true);$("settings").onclick=newSettings;$("newTop").onclick=newSettings;return api});
