(function(root,factory){const api=factory(root.QuizQuestions);if(typeof module==="object"&&module.exports)module.exports=api;root.BuzzerQuiz=api})(typeof globalThis!=="undefined"?globalThis:this,function(bank){"use strict";
function createState(config,questions){return{config,questions,index:0,scores:Array(config.players.length).fill(0),excluded:[],buzzed:null,locked:false}}
function buzz(state,player){if(state.locked||state.excluded.includes(player))return false;state.buzzed=player;state.locked=true;return true}
function judge(state,correct){if(state.buzzed===null)return{next:false};const player=state.buzzed;if(correct){state.scores[player]++;return{next:true,player}}if(state.config.penalty)state.scores[player]--;state.excluded.push(player);state.buzzed=null;state.locked=false;return{next:state.excluded.length>=state.config.players.length,player}}
function nextQuestion(state){state.index++;state.excluded=[];state.buzzed=null;state.locked=false;return state.index>=state.questions.length}
const api={createState,buzz,judge,nextQuestion};if(typeof document==="undefined")return api;
const $=id=>document.getElementById(id),screens=["setup","game","round","finish"],defaults=["#e33e50","#2878d0","#26965d","#e99419","#8d4cc6","#e55aa7","#168f9b","#6c7c2b"],symbols=["★","●","◆","▲","♥","☀","♣","⬟"];let state,timerId,remaining;
function show(id){screens.forEach(x=>$(x).hidden=x!==id);scrollTo({top:0,behavior:"smooth"})}
function renderPlayers(){const n=+$("playerCount").value;$("players").innerHTML=Array.from({length:n},(_,i)=>`<div class="player-row"><input class="symbol" value="${symbols[i]}" maxlength="2" aria-label="Symbol hráče ${i+1}"><input class="name" value="Hráč ${i+1}" aria-label="Jméno hráče ${i+1}"><input class="color" type="color" value="${defaults[i]}" aria-label="Barva hráče ${i+1}"></div>`).join("")}
function setup(){ $("categories").innerHTML=Object.entries(bank.categories).map(([k,v])=>`<label><input type="checkbox" value="${k}" checked> ${v}</label>`).join("");renderPlayers()}
function readConfig(){const categories=[...$("categories").querySelectorAll(":checked")].map(x=>x.value);if(!categories.length){$("error").textContent="Vyberte alespoň jednu kategorii.";return null}$("error").textContent="";return{players:[...document.querySelectorAll(".player-row")].map(r=>({symbol:r.querySelector(".symbol").value||"●",name:r.querySelector(".name").value.trim()||"Hráč",color:r.querySelector(".color").value})),count:+$("questionCount").value,difficulty:$("difficulty").value,seconds:+$("answerTime").value,penalty:$("penalty").checked,categories}}
function selectQuestions(c){let pool=bank.questions.filter(q=>c.categories.includes(q.category)&&(c.difficulty==="all"||q.difficulty===+c.difficulty));for(let i=pool.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[pool[i],pool[j]]=[pool[j],pool[i]]}return pool.slice(0,c.count)}
function renderScores(){ $("scores").innerHTML=state.config.players.map((p,i)=>`<span class="score-pill" style="--c:${p.color}">${p.symbol} ${state.scores[i]}</span>`).join("")}
function renderBuzzers(){ $("buzzers").innerHTML=state.config.players.map((p,i)=>`<button class="buzzer" data-player="${i}" style="--c:${p.color}">${p.symbol}<br>${p.name}</button>`).join("");updateBuzzers()}
function updateBuzzers(){document.querySelectorAll(".buzzer").forEach((b,i)=>{b.disabled=state.locked||state.excluded.includes(i);b.classList.toggle("chosen",state.buzzed===i)})}
function ask(){clearInterval(timerId);const q=state.questions[state.index];$("progress").textContent=`Otázka ${state.index+1} / ${state.questions.length}`;$("category").textContent=bank.categories[q.category];$("question").textContent=q.question;$("answerText").textContent=q.answer;$("answer").open=false;$("answerPanel").hidden=true;$("buzzHint").hidden=false;renderScores();renderBuzzers();show("game")}
function startAnswer(){remaining=state.config.seconds;$("answerPanel").hidden=false;$("buzzHint").hidden=true;const p=state.config.players[state.buzzed];$("buzzed").textContent=`${p.symbol} Odpovídá ${p.name}`;tick();clearInterval(timerId);timerId=setInterval(()=>{remaining--;tick();if(remaining<=0){clearInterval(timerId);handleJudge(false,"Čas vypršel")}},1000)}
function tick(){$("timer").textContent=`${remaining} s`}
function handleJudge(correct,label){clearInterval(timerId);const result=judge(state,correct);renderScores();if(correct||result.next){endQuestion(correct?`Správně – bod získává ${state.config.players[result.player].name}`:(label||"Nikdo správně neodpověděl"));return}$("answerPanel").hidden=true;$("buzzHint").hidden=false;$("buzzHint").textContent=`Špatně. Ostatní bzučáky jsou znovu odemčené.`;updateBuzzers()}
function endQuestion(title){clearInterval(timerId);$("roundTitle").textContent=title;$("roundAnswer").textContent=`Správná odpověď: ${state.questions[state.index].answer}`;$("next").textContent=state.index+1>=state.questions.length?"Výsledky":"Další otázka";show("round")}
function finish(){const max=Math.max(...state.scores);$("finalScores").innerHTML=state.config.players.map((p,i)=>`<div class="final ${state.scores[i]===max?"winner":""}" style="color:${p.color}">${p.symbol} ${p.name}: ${state.scores[i]} bodů${state.scores[i]===max?" 🏆":""}</div>`).join("");show("finish")}
function restart(settings){clearInterval(timerId);if(settings){renderPlayers();show("setup")}else{state=createState(state.config,selectQuestions(state.config));ask()}}
setup();$("playerCount").onchange=renderPlayers;$("start").onclick=()=>{const c=readConfig();if(!c)return;state=createState(c,selectQuestions(c));ask()};$("buzzers").onclick=e=>{const b=e.target.closest(".buzzer");if(b&&buzz(state,+b.dataset.player)){updateBuzzers();startAnswer()}};$("correct").onclick=()=>handleJudge(true);$("wrong").onclick=()=>handleJudge(false);$("skip").onclick=()=>endQuestion("Otázka přeskočena");$("next").onclick=()=>nextQuestion(state)?finish():ask();$("newTop").onclick=()=>restart(true);$("settings").onclick=()=>restart(true);$("again").onclick=()=>restart(false);document.addEventListener("visibilitychange",()=>{if(document.hidden)clearInterval(timerId)});
return api});
