(function(root,factory){const api=factory(root.ReflexThemes);if(typeof module==="object"&&module.exports)module.exports=api;root.ColorReflex=api})(typeof globalThis!=="undefined"?globalThis:this,function(themes){"use strict";
function balancedTargets(length,playerCount=4,random=Math.random){const out=[];while(out.length<length){const batch=Array.from({length:playerCount},(_,i)=>i);for(let i=batch.length-1;i;i--){const j=Math.floor(random()*(i+1));[batch[i],batch[j]]=[batch[j],batch[i]]}out.push(...batch)}return out.slice(0,length)}
function createState(config,targets){return{config,targets,index:0,scores:Array(config.players.length).fill(0),phase:"waiting",blocked:[],resolved:false}}
function expectedPlayer(s){const shown=s.targets[s.index];return s.config.mode==="opposite"?(shown+Math.floor(s.config.players.length/2))%s.config.players.length:shown}
function press(s,player){if(s.resolved)return{type:"ignored"};if(s.phase==="waiting"){s.scores[player]--;return{type:"early",player}}if(s.phase!=="shown"||s.blocked.includes(player))return{type:"ignored"};if(player===expectedPlayer(s)){s.scores[player]++;s.resolved=true;return{type:"correct",player}}s.scores[player]--;s.blocked.push(player);return{type:"wrong",player}}
function nextChallenge(s){s.index++;s.phase="waiting";s.blocked=[];s.resolved=false;return s.index>=s.targets.length||s.config.firstTo10&&Math.max(...s.scores)>=10}
const api={balancedTargets,createState,expectedPlayer,press,nextChallenge};if(typeof document==="undefined")return api;
const $=id=>document.getElementById(id),symbols=themes.default.playerSymbols,colors=["#df3b4e","#2878d0","#299254","#dd921b"];let state,delayId,revealId;
function show(id){$("setup").hidden=id!=="setup";$("arena").hidden=id!=="arena";$("finish").hidden=id!=="finish"}
function editors(){$("editors").innerHTML=Array.from({length:+$("playerCount").value},(_,i)=>`<div class="editor"><input class="name" value="Hráč ${i+1}" aria-label="Jméno hráče ${i+1}"><input class="color" type="color" value="${colors[i]}" aria-label="Barva hráče ${i+1}"><input class="symbol" maxlength="3" value="${symbols[i].fallback}" aria-label="Symbol hráče ${i+1}"></div>`).join("")}
function config(){return{mode:$("mode").value,firstTo10:$("length").value==="first10",length:$("length").value==="first10"?200:+$("length").value,players:[...document.querySelectorAll(".editor")].map((r,i)=>({name:r.querySelector(".name").value.trim()||`Hráč ${i+1}`,color:r.querySelector(".color").value,symbol:r.querySelector(".symbol").value||symbols[i].fallback,image:symbols[i].image,alt:symbols[i].alt}))}}
function symbolHtml(p){return p.image?`<img src="${p.image}" alt="${p.alt}" onerror="this.replaceWith(document.createTextNode('${p.symbol}'))">`:p.symbol}
function renderZones(){$("arena").classList.toggle("players-3",state.config.players.length===3);document.querySelectorAll(".zone").forEach((z,i)=>{const p=state.config.players[i];z.hidden=!p;if(!p)return;z.style.setProperty("--c",p.color);z.innerHTML=`<span class="symbol">${symbolHtml(p)}</span><span>${p.name}</span><span class="score">${state.scores[i]}</span>`;z.disabled=false;z.classList.remove("wrong","correct")})}
function rule(){return{symbol:"Stiskne majitel symbolu",color:"Stiskne hráč stejné barvy",combo:"Najdi stejný symbol i barvu",opposite:state.config.players.length===3?"TĚŽKÉ: stiskne následující hráč po směru hodin":"TĚŽKÉ: stiskne hráč v protějším rohu"}[state.config.mode]}
function waitChallenge(){clearTimeout(delayId);clearTimeout(revealId);state.phase="waiting";state.resolved=false;state.blocked=[];renderZones();$("progress").textContent=state.config.firstTo10?"První na 10 bodů":`${state.index+1} / ${state.targets.length}`;$("signal").textContent="…";$("signal").style.color="";$("rule").textContent="Čekej na signál";delayId=setTimeout(reveal,1000+Math.random()*3000)}
function reveal(){state.phase="shown";const shown=state.targets[state.index],p=state.config.players[shown];$("signal").innerHTML=state.config.mode==="color"?"●":symbolHtml(p);$("signal").style.color=state.config.mode==="symbol"?"#253050":p.color;$("rule").textContent=rule()}
function handle(player){const r=press(state,player),zone=document.querySelector(`[data-player="${player}"]`);if(r.type==="ignored")return;if(r.type==="early"||r.type==="wrong"){zone.classList.add("wrong");zone.querySelector(".score").textContent=state.scores[player];zone.disabled=true;setTimeout(()=>{zone.classList.remove("wrong");if(r.type==="early"&&state.phase==="waiting")zone.disabled=false},450);return}if(r.type==="correct"){zone.classList.add("correct");renderZones();zone.classList.add("correct");$("rule").textContent=`Správně, ${state.config.players[player].name}!`;revealId=setTimeout(()=>nextChallenge(state)?finish():waitChallenge(),750)}}
function finish(){clearTimeout(delayId);clearTimeout(revealId);const max=Math.max(...state.scores);$("results").innerHTML=state.config.players.map((p,i)=>`<div class="result ${state.scores[i]===max?"winner":""}" style="color:${p.color}">${p.symbol} ${p.name}: ${state.scores[i]} ${state.scores[i]===max?"🏆":""}</div>`).join("");show("finish")}
function start(same=false){const c=same?state.config:config();state=createState(c,balancedTargets(c.length,c.players.length));show("arena");renderZones();waitChallenge()}
function settings(){clearTimeout(delayId);clearTimeout(revealId);show("setup")}
editors();$("playerCount").onchange=editors;$("start").onclick=()=>start(false);document.querySelectorAll(".zone").forEach(z=>z.addEventListener("pointerdown",e=>{e.preventDefault();handle(+z.dataset.player)}));$("quit").onclick=settings;$("settings").onclick=settings;$("again").onclick=()=>start(true);return api});
