(function(root,factory){const api=factory(root.WhisperPrompts);if(typeof module==="object"&&module.exports)module.exports=api;root.PictureWhisper=api})(typeof globalThis!=="undefined"?globalThis:this,function(promptData){"use strict";
function createState(players,prompt){return{players:[...players],step:0,history:[{type:"text",text:prompt,player:null}],strokes:[],currentStroke:null}}
function stepType(state){return state.step%2===0?"drawing":"guess"}
function saveStep(state,value){state.history.push({type:stepType(state),player:state.players[state.step],...(stepType(state)==="drawing"?{strokes:value}:{text:value})});state.step++;state.strokes=[];state.currentStroke=null;return state.step>=state.players.length}
function clearState(state){state.history.length=0;state.strokes.length=0;state.currentStroke=null}
const api={createState,stepType,saveStep,clearState};if(typeof document==="undefined")return api;
const $=id=>document.getElementById(id),screens=["setup","handoff","secret","draw","guess","reveal"],colors=["#202433","#df3d4d","#2877c7","#249253","#efa51d","#8c4fc0"];let state,color=colors[0],width=4,erasing=false,drawing=false,revealed=0;const canvas=$("canvas"),ctx=canvas.getContext("2d"),guessCanvas=$("guessCanvas");
function show(id){screens.forEach(x=>$(x).hidden=x!==id);scrollTo({top:0,behavior:"smooth"})}
function renderPlayers(){const n=+$("playerCount").value;$("players").innerHTML=Array.from({length:n},(_,i)=>`<input class="player-name" value="Hráč ${i+1}" aria-label="Jméno hráče ${i+1}">`).join("")}
function prompt(){if(document.querySelector('[name=promptMode]:checked').value==="custom"){const t=$("customPrompt").value.trim().slice(0,40);if(!t){$("error").textContent="Napište vlastní zadání.";return null}return t}$("error").textContent="";return promptData.prompts[Math.floor(Math.random()*promptData.prompts.length)].text}
function handoff(){drawing=false;const p=state.players[state.step];$("handoffText").textContent=`Předat zařízení hráči ${p}`;show("handoff")}
function currentSource(){return state.history[state.history.length-1]}
function confirmed(){const type=stepType(state),p=state.players[state.step];if(type==="drawing"){$("secretText").textContent=currentSource().text;show("secret")}else{$("guessPlayer").textContent=`Hádá ${p}`;$("guessInput").value="";show("guess");requestAnimationFrame(()=>drawStored(guessCanvas,currentSource().strokes))}}
function startDrawing(){$("drawPlayer").textContent=`Kreslí ${state.players[state.step]}`;$("drawPrompt").textContent=currentSource().text;state.strokes=[];show("draw");requestAnimationFrame(()=>{resize();drawing=true})}
function resize(){const r=canvas.getBoundingClientRect(),d=Math.max(1,devicePixelRatio||1);canvas.width=r.width*d;canvas.height=r.height*d;ctx.setTransform(d,0,0,d,0,0);redraw()}
function drawStored(target,strokes){const r=target.getBoundingClientRect(),d=Math.max(1,devicePixelRatio||1);target.width=r.width*d;target.height=r.height*d;const c=target.getContext("2d");c.setTransform(d,0,0,d,0,0);c.clearRect(0,0,r.width,r.height);c.lineCap="round";c.lineJoin="round";strokes.forEach(s=>{c.strokeStyle=s.color;c.lineWidth=s.width;c.beginPath();c.moveTo(s.points[0].x*r.width,s.points[0].y*r.height);s.points.slice(1).forEach(p=>c.lineTo(p.x*r.width,p.y*r.height));if(s.points.length===1)c.lineTo(s.points[0].x*r.width+.01,s.points[0].y*r.height);c.stroke()})}
function redraw(){drawStored(canvas,state.strokes)}
function point(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height}}
function down(e){if(!drawing)return;canvas.setPointerCapture(e.pointerId);state.currentStroke={color:erasing?"#fff":color,width:erasing?width*2:width,points:[point(e)]};state.strokes.push(state.currentStroke);redraw()}
function move(e){if(state?.currentStroke){state.currentStroke.points.push(point(e));redraw()}}function up(){if(state)state.currentStroke=null}
function complete(value){if(saveStep(state,value)){renderReveal();show("reveal")}else handoff()}
function renderReveal(){revealed=0;$("timeline").innerHTML=state.history.map((s,i)=>`<article class="step hidden-step" data-index="${i}"><h3>${i===0?"Původní zadání":`${i}. ${s.player} – ${s.type==="drawing"?"kresba":"odhad"}`}</h3>${s.type==="drawing"?`<canvas data-drawing="${i}"></canvas>`:`<p></p>`}</article>`).join("");state.history.forEach((s,i)=>{const el=document.querySelector(`[data-index="${i}"]`);if(s.type==="text"||s.type==="guess")el.querySelector("p").textContent=s.text});$("revealNext").hidden=false;$("revealNext").textContent="Odhalit první krok"}
function revealTo(count){revealed=Math.min(count,state.history.length);document.querySelectorAll(".step").forEach((el,i)=>{el.classList.toggle("hidden-step",i>=revealed);if(i<revealed&&state.history[i].type==="drawing")drawStored(el.querySelector("canvas"),state.history[i].strokes)});$("revealNext").textContent=revealed>=state.history.length?"Vše odhaleno":"Odhalit další krok";$("revealNext").disabled=revealed>=state.history.length}
function newGame(){if(state)clearState(state);state=null;renderPlayers();$("customPrompt").value="";show("setup")}
renderPlayers();$("playerCount").onchange=renderPlayers;document.querySelectorAll('[name=promptMode]').forEach(r=>r.onchange=()=>{$("customPrompt").disabled=r.value!=="custom"||!r.checked});$("start").onclick=()=>{const p=prompt();if(!p)return;state=createState([...document.querySelectorAll(".player-name")].map((x,i)=>x.value.trim()||`Hráč ${i+1}`),p);handoff()};$("confirm").onclick=confirmed;$("drawStart").onclick=startDrawing;$("saveDrawing").onclick=()=>complete(structuredClone(state.strokes));$("saveGuess").onclick=()=>{const text=$("guessInput").value.trim().slice(0,40);if(!text){$("guessError").textContent="Napiš svůj odhad.";return}$("guessError").textContent="";complete(text)};$("revealNext").onclick=()=>revealTo(revealed+1);$("revealAll").onclick=()=>revealTo(state.history.length);$("again").onclick=newGame;$("newTop").onclick=newGame;
$("colors").innerHTML=colors.map(c=>`<button class="color ${c===color?"selected":""}" data-color="${c}" aria-label="Barva ${c}" style="--c:${c}"></button>`).join("");$("colors").onclick=e=>{if(!e.target.dataset.color)return;color=e.target.dataset.color;erasing=false;$("eraser").classList.remove("selected");document.querySelectorAll(".color").forEach(x=>x.classList.toggle("selected",x===e.target))};document.querySelector(".tools").onclick=e=>{if(e.target.dataset.width){width=+e.target.dataset.width;document.querySelectorAll("[data-width]").forEach(x=>x.classList.toggle("selected",x===e.target))}};$("eraser").onclick=()=>{erasing=!erasing;$("eraser").classList.toggle("selected",erasing)};$("undo").onclick=()=>{state.strokes.pop();redraw()};$("clear").onclick=()=>{state.strokes=[];redraw()};canvas.addEventListener("pointerdown",down);canvas.addEventListener("pointermove",move);canvas.addEventListener("pointerup",up);canvas.addEventListener("pointercancel",up);canvas.addEventListener("lostpointercapture",up);addEventListener("resize",()=>{if(!canvas.closest("[hidden]"))resize()});return api});
