(function(root,factory){const api=factory();if(typeof module==="object"&&module.exports)module.exports=api;root.MiniOlympics=api})(typeof globalThis!=="undefined"?globalThis:this,function(){"use strict";
function pointsFor(count){if(count===4)return[5,3,2,1];return Array.from({length:count},(_,i)=>count-i)}
function awardPoints(results,compare,count){const sorted=results.map((result,player)=>({result,player})).sort((a,b)=>compare(a.result,b.result)),base=pointsFor(count),awards=Array(count).fill(0);for(let i=0;i<sorted.length;){let j=i+1;while(j<sorted.length&&compare(sorted[i].result,sorted[j].result)===0)j++;const avg=base.slice(i,j).reduce((a,b)=>a+b,0)/(j-i);for(let k=i;k<j;k++)awards[sorted[k].player]=avg;i=j}return{sorted,awards}}
const api={pointsFor,awardPoints};if(typeof document==="undefined")return api;
const $=id=>document.getElementById(id),screens=["setup","handoff","play","saved","disciplineResult","finish"];let state;
function show(id){screens.forEach(x=>$(x).hidden=x!==id);scrollTo({top:0,behavior:"smooth"})}
function renderPlayers(){const n=+$("playerCount").value;$("players").innerHTML=Array.from({length:n},(_,i)=>`<input class="player-name" value="Hráč ${i+1}" aria-label="Jméno hráče ${i+1}">`).join("")}
function disciplines(){return window.MiniDisciplines}
function setupDisciplines(){$("disciplineList").innerHTML=disciplines().map((d,i)=>`<label><input type="checkbox" value="${d.id}" checked> ${i+1}. ${d.title}</label>`).join("")}
function begin(){const selected=[...$("disciplineList").querySelectorAll(":checked")].map(x=>x.value);if(!selected.length){$("error").textContent="Vyberte alespoň jednu disciplínu.";return}$("error").textContent="";const players=[...document.querySelectorAll(".player-name")].map((x,i)=>x.value.trim()||`Hráč ${i+1}`);state={players,disciplines:selected.map(id=>disciplines().find(d=>d.id===id)),discipline:0,player:0,results:[],scores:Array(players.length).fill(0)};handoff()}
function current(){return state.disciplines[state.discipline]}
function handoff(){const d=current();$("disciplineProgress").textContent=`Disciplína ${state.discipline+1} / ${state.disciplines.length}: ${d.title}`;$("handoffText").textContent=`Předat zařízení hráči ${state.players[state.player]}`;show("handoff")}
function startAttempt(){const d=current();$("currentPlayer").textContent=`Závodí ${state.players[state.player]}`;$("disciplineTitle").textContent=d.title;$("instructions").textContent=d.instructions;$("stage").innerHTML="";show("play");d.start(state.players[state.player])}
function attemptDone(){const d=current();state.results[state.player]=d.getResult();d.cleanup();$("stage").replaceChildren();show("saved")}
function advancePlayer(){state.player++;if(state.player<state.players.length){handoff();return}showDisciplineResult()}
function format(value){return typeof value==="number"?Math.round(value*100)/100:String(value)}
function showDisciplineResult(){const d=current(),rank=awardPoints(state.results,d.compareResults,state.players.length);rank.awards.forEach((p,i)=>state.scores[i]+=p);$("resultTitle").textContent=d.title;$("resultTable").innerHTML=rank.sorted.map((x,i)=>`<div class="score-row"><strong>${i+1}.</strong><span>${state.players[x.player]}</span><span class="detail">${d.resultLabel||"Výsledek"}</span><strong>${format(x.result)} · +${rank.awards[x.player]}</strong></div>`).join("");$("nextDiscipline").textContent=state.discipline+1>=state.disciplines.length?"Celkové výsledky":"Další disciplína";show("disciplineResult")}
function advanceDiscipline(){state.discipline++;if(state.discipline>=state.disciplines.length){finishGame();return}state.player=0;state.results=[];handoff()}
function finishGame(){const max=Math.max(...state.scores),order=state.players.map((name,i)=>({name,i,score:state.scores[i]})).sort((a,b)=>b.score-a.score);$("finalTable").innerHTML=order.map((x,i)=>`<div class="score-row ${x.score===max?"winner":""}"><strong>${i+1}.</strong><span>${x.name}</span><span class="detail">Celkem</span><strong>${x.score} b. ${x.score===max?"🏆":""}</strong></div>`).join("");show("finish")}
function cleanup(){if(state?.disciplines)state.disciplines.forEach(d=>d.cleanup());$("stage").replaceChildren()}
function reset(){cleanup();state=null;renderPlayers();show("setup")}
renderPlayers();setupDisciplines();$("playerCount").onchange=renderPlayers;$("start").onclick=begin;$("confirm").onclick=startAttempt;document.addEventListener("discipline-finish",attemptDone);$("continue").onclick=advancePlayer;$("nextDiscipline").onclick=advanceDiscipline;$("newTop").onclick=reset;$("settings").onclick=reset;$("again").onclick=()=>{const players=state.players,ds=state.disciplines;cleanup();state={players,disciplines:ds,discipline:0,player:0,results:[],scores:Array(players.length).fill(0)};handoff()};return api});
